Correcting old (and broken) links in /aas/README.md
admin-shell-io/id pull request #15
Opened 2020-11-01 14:32 UTC by sebbader

2020-11-01 15:07 UTC, sebbader commented
@BirgitBoss, please see if this solves #13

2020-11-01 19:48 UTC, BirgitBoss requested changes
please check path to template again, probably branch name missing? Thanks

2020-11-01 19:48 UTC, BirgitBoss commented on README.md
> +- Create a README following the template in https://github.com/admin-shell-io/id/templates/README.md
does not work, probably branch name is missing in path?

2020-11-01 19:48 UTC, BirgitBoss commented on README.md
> +- Attach the filled [template](https://github.com/admin-shell-io/id/templates/README.md)
see above: does not work, probably branch name is missing in path?

2020-11-02 13:55 UTC, sebbader commented
Thanks for reviewing, @BirgitBoss! Now it's fixed.

2022-04-28 11:29 UTC, merged