ID Repository for InterOpera AAS-Submodels
admin-shell-io/id pull request #28
Opened 2023-05-03 11:06 UTC by quickhdsdc

28 AAS submodel templates are being developed in the [InterOpera ](https://interopera.de/teilmodellprojekte/)Project. We would like to store the properties and their temporary semanticID here in IDTA repository.

2023-06-15 13:38 UTC, sebbader-sap requested changes
Thanks for the contribution! Please see my comments. In addition, please think about adding `major version` -> `revision` information in the URIs and reflect this also in the folder structure.

2023-06-15 13:38 UTC, sebbader-sap commented on InterOpera/NameplateLaserEngravingMachine/README.md
> +https://admin-shell.io/id/InterOpera/NameplateLaserEngravingMachine/MaxLaserPower
Please follow a pattern like `https://admin-shell.io/InterOpera/NameplateLaserEngravingMachine/<version>/<revision>/MaxLaserPower`

2023-06-15 13:38 UTC, sebbader-sap commented on InterOpera/NameplateLaserEngravingMachine/README.md
> +This sub-namespace is proposed by [Dachuan Shi](mailto:dachuan.shi@ipa.fraunhofer.de), [Fraunhofer IPA](https://www.ipa.fraunhofer.de/en/expertise/digitools-for-manufacturing.html). Alternatively, [O
Is there an official InterOpera contact? People tend to leave organisations sometimes :-)

2023-06-15 13:38 UTC, sebbader-sap commented on InterOpera/TechnicalDataLaserEngravingMachine/README.md
> +https://admin-shell.io/id/InterOpera/TechnicalDataLaserEngravingMachine/BeamDiameter
Please see my comment on the URI structure above.

2023-07-06 10:13 UTC, quickhdsdc reviewed
The comments have been addressed.

2023-07-10 14:39 UTC, sebbader-sap requested changes
Please see my comment about the "id" segment. Rest looks good!

2023-07-10 14:39 UTC, sebbader-sap commented on InterOpera/NameplateLaserEngravingMachine/README.md
> +https://admin-shell.io/id/InterOpera/NameplateLaserEngravingMachine/1/0/MaxLaserPower
Please remove the `id` path segment: https://admin-shell.io/id/InterOpera/NameplateLaserEngravingMachine/1/0/MaxLaserPower --> https://admin-shell.io/InterOpera/NameplateLaserEngravingMachine/1/0/MaxLaserPower

Also for the other URIs.

2023-07-12 09:17 UTC, sebbader-sap reviewed
Thanks for the update! I hereby confirm that the proposal is formally correct. Next step to get the final approval:
I will take the PR and present it in the "IDTA WS AAS" on July 19th. 
As soon as we have that, I will approve and merge the PR.

2023-07-19 07:47 UTC, sebbader-sap commented
The AAS WS has approved the proposed identifiers.

2023-07-19 08:12 UTC, quickhdsdc commented
> The AAS WS has approved the proposed identifiers.

Thank you!

2023-07-26 12:46 UTC, sebbader-sap approved these changes

2023-07-26 12:47 UTC, merged