AAS V3 Classes and Attribute Identifiers
admin-shell-io/id pull request #31
Opened 2024-11-25 11:02 UTC by sebbader-sap

2024-11-25 14:05 UTC, BirgitBoss commented on aas/3/0/README.md
> +This is the sub-namespace reserved for the Asset Administration Shell Metamodel version 3.0.
```suggestion
This is the sub-namespace reserved for the Asset Administration Shell Metamodel version 3.0 (IDTA-01001-3-0).
```

2024-11-25 14:06 UTC, BirgitBoss commented on aas/3/0/README.md
> +The Metamodel itself is defined in the 'Details of the Asset Administration Shell - Part 1'. Only classes, attributes and named entities used in this model are allowed in this sub-namespace. The Meta
```suggestion
The Metamodel itself is defined in the 'IDTA-01001-3-0 Specification of the Asset Administration Shell - Part 1: Metamodel'. Only classes, attributes and named entities used in this model are allowed in this sub-namespace. The Metamodel is the core resource for the structure of the Asset Administration Shell and provides the frame for all further specifications. The following entities are defined in the Metamodel but also serve as an example how to use the 'Asset Administration Shell Identifiers' in general.
```

2024-11-25 14:07 UTC, BirgitBoss commented on aas/3/0/README.md
> +The sub-namespace AAS and its identifiers have been accepted by the Coordination Board.
```suggestion
The sub-namespace AAS and its identifiers have been accepted by the Coordination Board.
The identifiers are derived following the grammar as defined in IDTA-01001-3-0. 
```

2024-11-25 14:09 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## AdministrativeInformation
 Every Identifiable may have administrative information. Administrative information includes for example  Information about the version of the element  Information about who created or who made the last change to the element  Information about the languages available in case the element contains text, for translating purposed also themmaster or default language may be definedIn the first version of the AAS metamodel only version information as defined by IEC 61360 is defined. In later versions additional attributes may be added.

 [http://admin-shell.io/aas/3/0/AdministrativeInformation](http://admin-shell.io/aas/3/0/AdministrativeInformation) The AdministrativeInformation class as defined in IDTA-01001-3-0.

## AdministrativeInformation/creator
  The subject ID of the subject responsible for making the element 

 [http://admin-shell.io/aas/3/0/AdministrativeInformation/creator](http://admin-shell.io/aas/3/0/AdministrativeInformation/creator) The attribute creator of the AdministrativeInformation class as defined in IDTA-01001-3-0.


## AdministrativeInformation/templateId
  Identifier of the template that guided the creation of the element

 [http://admin-shell.io/aas/3/0/AdministrativeInformation/creator](http://admin-shell.io/aas/3/0/AdministrativeInformation/templateId) The attribute templateId of the AdministrativeInformation class as defined in IDTA-01001-3-0.
 
## AdministrativeInformation/revision
 Revision of the element. Constraint AASd-005: A revision requires a version. This means, if there is no version there is no revision neither.

 [http://admin-shell.io/aas/3/0/AdministrativeInformation/revision](http://admin-shell.io/aas/3/0/AdministrativeInformation/revision) The attribute revision of the AdministrativeInformation class as defined in IDTA-01001-3-0.

## AdministrativeInformation/version
 Version of the element.

 [http://admin-shell.io/aas/3/0/AdministrativeInformation/version](http://admin-shell.io/aas/3/0/AdministrativeInformation/version) The attribute version of the AdministrativeInformation class as defined in IDTA-01001-3-0.


```

2024-11-25 14:14 UTC, BirgitBoss commented on aas/3/0/README.md
> +
two new attribute: creator and templateId
update text of AdministrativeInforamtion

2024-11-25 14:17 UTC, BirgitBoss commented on aas/3/0/README.md
> + Denotes whether the Asset of of kind 'Type' or 'Instance'.
```suggestion
 Denotes whether the Asset of of kind 'Type' or 'Instance' or of kind 'not applicable'.
```

2024-11-25 14:17 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## AssetInformation/assetType
 In case AssetInformation/assetKind is applicable the AssetInformation/assetType is the asset ID of the type asset of the asset under consideration as identified by AssetInformation/globalAssetId.

 [https://admin-shell.io/aas/3/0/AssetInformation/assetType](https://admin-shell.io/aas/3/0/AssetInformation/assetType) The attribute assetType of the AssetInformation class as defined in IDTA-01001-3-0.
```

2024-11-25 14:19 UTC, BirgitBoss commented on aas/3/0/README.md
> + [https://admin-shell.io/aas/3/0/AssetInformation/externalAssetId](https://admin-shell.io/aas/3/0/AssetInformation/externalAssetId) The attribute externalAssetId of the AssetInformation class as defi
```suggestion
## AssetInformation/specificAssetId
 Additional domain specific external, typically proprietary Identifier for the asset like e.g. serial number etc.

 [https://admin-shell.io/aas/3/0/AssetInformation/specificAssetId](https://admin-shell.io/aas/3/0/AssetInformation/specificAssetId) The attribute specificAssetId of the AssetInformation class as defined in IDTA-01001-3-0.
```

2024-11-25 14:19 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## AssetInformation/defaultThumbnail
 Thumbnail of the asset represented by the asset administration shell.

 [https://admin-shell.io/aas/3/0/AssetInformation/defaultThumbnail](https://admin-shell.io/aas/3/0/AssetInformation/defaultThumbnail) The attribute thumbnail of the AssetInformation class as defined in IDTA-01001-3-0'.

```

2024-11-25 14:20 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/AssetAdministrationShell/security](http://admin-shell.io/aas/3/0/AssetAdministrationShell/security) The attribute security of the AssetAdministrationShell class as def
```suggestion

```

2024-11-25 14:20 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/AssetAdministrationShell/security](http://admin-shell.io/aas/3/0/AssetAdministrationShell/security) The attribute security of the AssetAdministrationShell class as def
no seucrity any longer in V3.0

2024-11-25 14:21 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/AssetAdministrationShell/submodel](http://admin-shell.io/aas/3/0/AssetAdministrationShell/submodel) The attribute submodel of the AssetAdministrationShell class as def
```suggestion
 [http://admin-shell.io/aas/3/0/AssetAdministrationShell/submodels](http://admin-shell.io/aas/3/0/AssetAdministrationShell/submodels) The attribute submodel of the AssetAdministrationShell class as defined in IDTA-01001-3-0.
```

2024-11-25 14:22 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

```

2024-11-25 14:22 UTC, BirgitBoss commented on aas/3/0/README.md
> +## AssetKind/INSTANCE
the speicficaion says "Instance" - should we define in grammar that enumeration values have capital letters always?

2024-11-25 14:25 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## BasicEventElement/observed
 Reference to the data or other elements that are being observed.

 [http://admin-shell.io/aas/3/0/BasicEventElement/observed](http://admin-shell.io/aas/3/0/BasicEventElement/observed) The attribute observed of the BasicEventElement class as defined in IDTA-01001-3-0'.

```

2024-11-25 14:26 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

```

2024-11-25 14:27 UTC, BirgitBoss commented on aas/3/0/README.md
> +## Entity/globalAssetId
ordering

2024-11-25 14:28 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## Entity/specificAssetId
 Reference to an identifier key value pair representing an external identifier of the asset represented by the asset administration shell.

 [http://admin-shell.io/aas/3/0/Entity/specificAssetId](http://admin-shell.io/aas/3/0/Entity/specificAssetId) The attribute specificAssetId of the Entity class as defined in IDTA-01001-3-0.

```

2024-11-25 14:28 UTC, BirgitBoss commented on aas/3/0/README.md
> + An extension of the element.
```suggestion
 Name of the extension.
```

2024-11-25 14:28 UTC, BirgitBoss commented on aas/3/0/README.md
> +## Extension/value
ordering

2024-11-25 14:29 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## EventElement
An event element.


 [http://admin-shell.io/aas/3/0/EventElement](http://admin-shell.io/aas/3/0/EventElement) The EventElement class as defined in Details of the IDTA-01001-3-0.

```

2024-11-25 14:30 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## File/contentType
 Content type of the content of the File.

 [https://admin-shell.io/aas/3/0/File/contentType](https://admin-shell.io/aas/3/0/File/contentType) The attribute mimeType of the File class as defined in IDTA-01001-3-0.

```

2024-11-25 14:30 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/Formula](http://admin-shell.io/aas/3/0/Formula) The Formula class as defined in Details of the 'Asset Administration Shell - Part 1 - Version 3.0'.
```suggestion
```

2024-11-25 14:30 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

```

2024-11-25 14:31 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## HasSemantics/supplementalSemanticId
 Identifier of a supplemental semantic definition of the element called supplemental semantic ID of the element

 [http://admin-shell.io/aas/3/0/HasSemantics/supplementalSemanticId](http://admin-shell.io/aas/3/0/HasSemantics/supplementalSemanticId) The attribute supplementalSemanticId of the HasSemantics class as defined in IDTA-01001-3-0.

```

2024-11-25 14:32 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/Identifiable/identification](http://admin-shell.io/aas/3/0/Identifiable/identification) The attribute identification of the Identifiable class as defined in 'Details o
```suggestion
## Identifiable/id
 The globally unique identification of the element.

 [http://admin-shell.io/aas/3/0/Identifiable/id](http://admin-shell.io/aas/3/0/Identifiable/id) The attribute identification of the Identifiable class as defined in IDTA-01001-3-0.
```

2024-11-25 14:33 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/ModelingKind](http://admin-shell.io/aas/3/0/ModelingKind) The ModelingKind class as defined in Details of the 'Asset Administration Shell - Part 1 - Version 3.0'.
```suggestion
## ModellingKind
 Enumeration for denoting whether an element is a type or an instance.

 [http://admin-shell.io/aas/3/0/ModellingKind](http://admin-shell.io/aas/3/0/ModellingKind) The ModellingKind class as defined IDTA-01001-3-0.
```

2024-11-25 14:33 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

```

2024-11-25 14:34 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion


```

2024-11-25 14:34 UTC, BirgitBoss commented on aas/3/0/README.md
> +
gab es so wohl noch nie? Immer geerbt von Referable

2024-11-25 14:35 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## Property/propertyValueId
 Reference to the global unqiue id of a coded value.

 [http://admin-shell.io/aas/3/0/Property/valueId](http://admin-shell.io/aas/3/0/Property/valueId) The attribute valueId of the Property class as defined in IDTA-01001-3-0.

```

2024-11-25 14:36 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## Qualifier/kind
 The qualifier kind describes the kind of qualifier that is applied to the element.

 [http://admin-shell.io/aas/3/0/Qualifier/kind](http://admin-shell.io/aas/3/0/Qualifier/kind) The attribute kind of the Qualifier class as defined in IDTA-01001-3-0.
```

2024-11-25 14:36 UTC, BirgitBoss commented on aas/3/0/README.md
> +
# Qualifier/valueType
  Data type of the qualifier value.

 [http://admin-shell.io/aas/3/0/Qualifier/valueType](http://admin-shell.io/aas/3/0/Qualifier/valueType) The attribute valueType of the Qualifier class as defined in IDTA-01001-3-0.

2024-11-25 14:37 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

# Qualifier/valueType
  Data type of the qualifier value.

 [http://admin-shell.io/aas/3/0/Qualifier/valueType](http://admin-shell.io/aas/3/0/Qualifier/valueType) The attribute valueType of the Qualifier class as defined in IDTA-01001-3-0.
 
```

2024-11-25 14:37 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion


```

2024-11-25 14:38 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

## Resource
 Resource represents an address to a file (a locator). The value is a URI that can represent an absolute or relative path.

 [http://admin-shell.io/aas/3/0/Resource](http://admin-shell.io/aas/3/0/Resource) The Resource class as defined in IDTA-01001-3-0.

## Resource/contentType
 Content type of the content of the file

 The content type states which file extensions the file can have.

 [http://admin-shell.io/aas/3/0/Resource/contentType](http://admin-shell.io/aas/3/0/Resource/contentType) The attribute contentType of the Resource class as defined in IDTA-01001-3-0.
 
## Resource/path
 Path and name of the resource (with file extension)
 
 The path can be absolute or relative.

 [http://admin-shell.io/aas/3/0/Resource/path](http://admin-shell.io/aas/3/0/Resource/path) The attribute path of the Resource class as defined in IDTA-01001-3-0.
 
## SpecificAssetId
 A specific asset ID describes a generic supplementary identifying attribute of the asset. The specific asset ID is not necessarily globally unique.

 [http://admin-shell.io/aas/3/0/SpecificAssetId](http://admin-shell.io/aas/3/0/SpecificAssetId) The SpecificAssetId class as defined in IDTA-01001-3-0.
 
## SpecificAssetId/name
 Name of the asset identifier.

 [http://admin-shell.io/aas/3/0/SpecificAssetId/name](http://admin-shell.io/aas/3/0/SpecificAssetId/name) The attribute name  of the SpecificAsetId class as defined in IDTA-01001-3-0.
 
## SpecificAssetId/externalSubjectId
 vThe unique ID of the (external) subject the specific asset ID value belongs to or has meaning to.

 [http://admin-shell.io/aas/3/0/SpecificAssetId/externalSubjectId](http://admin-shell.io/aas/3/0/SpecificAssetId/externalSubjectId) The attribute externalSubjectId  of the SpecificAsetId class as defined in IDTA-01001-3-0.

## SpecificAssetId/value
 value of the asset identifier.

 [http://admin-shell.io/aas/3/0/SpecificAssetId/value](http://admin-shell.io/aas/3/0/SpecificAssetId/value) The attribute value  of the SpecificAsetId class as defined in IDTA-01001-3-0.

```

2024-11-25 14:39 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/Submodel/submodelElement](http://admin-shell.io/aas/3/0/Submodel/submodelElement) The attribute submodelElement of the Submodel class as defined in 'Details of the Ass
```suggestion
## Submodel/submodelElements
 A submodel consists of zero or more submodel elements.

 [http://admin-shell.io/aas/3/0/Submodel/submodelElements](http://admin-shell.io/aas/3/0/Submodel/submodelElements) The attribute submodelElement of the Submodel class as defined in IDTA-01001-3-0.
```

2024-11-25 14:40 UTC, BirgitBoss approved these changes
In general: substitute `'Details of the Asset Administration Shell - Part 1 - Version 3.0'` with `IDTA-01001-3-0` (or `IDTA-01001-3-0 Specification of the Asset Administration Shell - Part 1: Metamodel`)

to be clarified: Handling of enumeration values: here all values are capital letter only , in specification it differs

2024-11-25 14:45 UTC, BirgitBoss commented on aas/3/README.md
>  # AAS Metamodel Version 3
```suggestion
# AAS Metamodel Version 3.0
```

2024-11-25 17:11 UTC, BirgitBoss commented on aas/3/0/README.md
> +## Range/min
ordering

2024-11-25 17:12 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

## Range/valueType
 Data type of the min und max attributes

 [http://admin-shell.io/aas/3/0/Range/valueType](http://admin-shell.io/aas/3/0/Range/valueType) The attribute valueType of the Range class as defined in IDTA-01001-3-0.
 
```

2024-11-25 17:16 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

## AasIdentifiables
 Enumeration of all referable elements within an asset administration shell. Contains IdentifiableElements

 [http://admin-shell.io/aas/3/0/AasIdentifiables](http://admin-shell.io/aas/3/0/AasIdentifiables) The AasIdentifiables class as defined in IDTA-01001-3-0.
 
## AasSubmodelElements
 Enumeration of all referable elements within an asset administration shell. Contains IdentifiableElements

 [http://admin-shell.io/aas/3/0/AasSubmodelElements](http://admin-shell.io/aas/3/0/AasSubmodelElements) The AasSubmodelElements class as defined in IDTA-01001-3-0.


## AasSubmodelElements/ANNOTATED_RELATIONSHIP_ELEMENT


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/ANNOTATED_RELATIONSHIP_ELEMENT](http://admin-shell.io/aas/3/0/AasSubmodelElements/ANNOTATED_RELATIONSHIP_ELEMENT) The AasSubmodelElements ANNOTATED_RELATIONSHIP_ELEMENT of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/BASIC_EVENT_ELEMENT


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/BASIC_EVENT_ELEMENT](http://admin-shell.io/aas/3/0/AasSubmodelElements/BASIC_EVENT_ELEMENT) The AasSubmodelElements BASIC_EVENT_ELEMENT of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/BLOB


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/BLOB](http://admin-shell.io/aas/3/0/AasSubmodelElements/BLOB) The AasSubmodelElements BLOB of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/CAPABILITY

 [http://admin-shell.io/aas/3/0/AasSubmodelElements/CAPABILITY](http://admin-shell.io/aas/3/0/AasSubmodelElements/CAPABILITY) The AasSubmodelElements CAPABILITY of the AasSubmodelElements class as defined in IDTA-01001-3-0.


## AasSubmodelElements/DATA_ELEMENT


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/DATA_ELEMENT](http://admin-shell.io/aas/3/0/AasSubmodelElements/DATA_ELEMENT) The AasSubmodelElements DATA_ELEMENT of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/ENTITY


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/ENTITY](http://admin-shell.io/aas/3/0/AasSubmodelElements/ENTITY) The AasSubmodelElements ENTITY of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/EVENT_ELEMENT


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/EVENT_ELEMENT](http://admin-shell.io/aas/3/0/AasSubmodelElements/EVENT_ELEM;ENT) The AasSubmodelElements EVENT_ELEMENT of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## ReferableElement/MULTI_LANGUAGE_PROPERTY
 Property with a value that can be provided in multiple languages.

 [http://admin-shell.io/aas/3/0/AasSubmodelElements/MULTI_LANGUAGE_PROPERTY](http://admin-shell.io/aas/3/0/AasSubmodelElements/MULTI_LANGUAGE_PROPERTY) The AasSubmodelElements MULTI_LANGUAGE_PROPERTY of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/OPERATION


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/OPERATION](http://admin-shell.io/aas/3/0/AasSubmodelElements/OPERATION) The AasSubmodelElements OPERATION of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/PROPERTY


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/PROPERTY](http://admin-shell.io/aas/3/0/AasSubmodelElements/PROPERTY) The AasSubmodelElements PROPERTY of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/RANGE


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/RANGE](http://admin-shell.io/aas/3/0/AasSubmodelElements/RANGE) The AasSubmodelElements RANGE of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/REFERENCE_ELEMENT


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/REFERENCE_ELEMENT](http://admin-shell.io/aas/3/0/AasSubmodelElements/REFERENCE_ELEMENT) The AasSubmodelElements REFERENCE_ELEMENT of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/RELATIONSHIP_ELEMENT


 [http://admin-shell.io/aas/3/0/AasSubmodelElements/RELATIONSHIPT_ELEMENT](http://admin-shell.io/aas/3/0/AasSubmodelElements/RELATIONSHIPT_ELEMENT) The AasSubmodelElements RELATIONSHIPT_ELEMENT of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/SUBMODEL_ELEMENT_COLLECTION
 Collection of Submodel Elements

 [http://admin-shell.io/aas/3/0/AasSubmodelElements/SUBMODEL_ELEMENT_COLLECTION](http://admin-shell.io/aas/3/0/AasSubmodelElements/SUBMODEL_ELEMENT_COLLECTION) The AasSubmodelElements SUBMODEL_ELEMENT_COLLECTION of the AasSubmodelElements class as defined in IDTA-01001-3-0.
 
## AasSubmodelElements/SUBMODEL_ELEMENT_LIST
 List of set of Submodel Elements

 [http://admin-shell.io/aas/3/0/AasSubmodelElements/SUBMODEL_ELEMENT_LIST](http://admin-shell.io/aas/3/0/AasSubmodelElements/SUBMODEL_ELEMENT_LIST) The AasSubmodelElements SUBMODEL_ELEMENT_LIST of the AasSubmodelElements class as defined in IDTA-01001-3-0.

## AasSubmodelElements/SUBMODEL_ELEMENT

 [http://admin-shell.io/aas/3/0/AasSubmodelElements/SUBMODEL_ELEMENT](http://admin-shell.io/aas/3/0/AasSubmodelElements/SUBMODEL_ELEMENT) The AasSubmodelElements SUBMODEL_ELEMENT of the AasSubmodelElements class as defined in IDTA-01001-3-0.

```

2024-11-25 17:17 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## Reference/referredSemanticId
 Expected semantic ID of the referenced model element (Reference/type=ModelReference); there typically is no semantic ID for for the referenced object of external references (Reference/type=ExternalReference).

 [https://admin-shell.io/aas/3/0/Reference/key](https://admin-shell.io/aas/3/0/Reference/referredSemanticId) The attribute referredSemanticId of the Reference class as defined in IDTA-01001-3-0.

## Reference/type
 Type of the reference
Denotes whether reference is an external reference or a model reference

 [https://admin-shell.io/aas/3/0/Reference/type](https://admin-shell.io/aas/3/0/Reference/type) The attribute type of the Reference class as defined in IDTA-01001-3-0.

```

2024-11-25 17:18 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## ReferenceElement/value
 External reference to an external object or entity or a logical reference to another element within the same or another Asset Administration Shell (i.e. a model reference to a Referable)

 [http://admin-shell.io/aas/3/0/ReferenceElement/value](http://admin-shell.io/aas/3/0/ReferenceElement/value) The attribute value of the ReferenceElement class as defined in IDTA-01001-3-0.

```

2024-11-25 17:19 UTC, BirgitBoss commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/SubmodelElementCollection/ordered](http://admin-shell.io/aas/3/0/SubmodelElementCollection/ordered) The attribute ordered of the SubmodelElementCollection class as def
```suggestion

```

2024-11-25 17:21 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## SubmodelElementList
 List or set of submodel elements.

 [http://admin-shell.io/aas/3/0/SubmodelElementListhttp://admin-shell.io/aas/3/0/SubmodelElementList) The SubmodelElementList class as defined in IDTA-01001-3-0.
 
## SubmodelElementList/orderRelevant
 Defines whether order in list is relevant. If orderRelevant = false, the list represents a set or a bag.

Default: True

 [http://admin-shell.io/aas/3/0/SubmodelElementList/orderRelevant](http://admin-shell.io/aas/3/0/SubmodelElementList/orderRelevant) The attribute orderRelevant of the SubmodelElementList class as defined in IDTA-01001-3-0.

## SubmodelElementList/semanticIdListElement
 Semantic ID which the submodel elements contained in the list match

 [http://admin-shell.io/aas/3/0/SubmodelElementList/semanticIdListElement](http://admin-shell.io/aas/3/0/SubmodelElementList/semanticIdListElement) The attribute semanticIdListElement of the SubmodelElementList class as defined in IDTA-01001-3-0.
 
## SubmodelElementList/typeValueListElement
 The submodel element type of the submodel elements contained in the list

 [http://admin-shell.io/aas/3/0/SubmodelElementList/typeValueListElement](http://admin-shell.io/aas/3/0/SubmodelElementList/typeValueListElement) The attribute typeValueListElement of the SubmodelElementList class as defined in IDTA-01001-3-0.


## SubmodelElementList/value
 Submodel elements contained in the list.

 [https://admin-shell.io/aas/3/0/SubmodelElementList/value](https://admin-shell.io/aas/3/0/SubmodelElementList/value)The attribute value of the SubmodelElementList class as defined in IDTA-01001-3-0.

## SubmodelElementList/valueTypeListElement
 The submodel element type of the submodel elements contained in the list

 [http://admin-shell.io/aas/3/0/SubmodelElementList/valueTypeListElement](http://admin-shell.io/aas/3/0/SubmodelElementList/valueTypeListElement) The attribute valueTypeListElement of the SubmodelElementList class as defined in IDTA-01001-3-0.

```

2024-11-25 17:42 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion
## AasReferableNonIdentifiables
 Enumeration of all referable elements within an asset administration shell. Contains IdentifiableElements

 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables) The AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.


## AasReferableNonIdentifiables/ANNOTATED_RELATIONSHIP_ELEMENT


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/ANNOTATED_RELATIONSHIP_ELEMENT](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/ANNOTATED_RELATIONSHIP_ELEMENT) The AasReferableNonIdentifiables ANNOTATED_RELATIONSHIP_ELEMENT of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/BASIC_EVENT_ELEMENT


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/BASIC_EVENT_ELEMENT](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/BASIC_EVENT_ELEMENT) The AasReferableNonIdentifiables BASIC_EVENT_ELEMENT of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/BLOB


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/BLOB](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/BLOB) The AasReferableNonIdentifiables BLOB of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/CAPABILITY

 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/CAPABILITY](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/CAPABILITY) The AasReferableNonIdentifiables CAPABILITY of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.


## AasReferableNonIdentifiables/DATA_ELEMENT


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/DATA_ELEMENT](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/DATA_ELEMENT) The AasReferableNonIdentifiables DATA_ELEMENT of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/ENTITY


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/ENTITY](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/ENTITY) The AasReferableNonIdentifiables ENTITY of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.
 

## AasReferableNonIdentifiables/EVENT_ELEMENT


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/EVENT_ELEMENT](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/EVENT_ELEM;ENT) The AasReferableNonIdentifiables EVENT_ELEMENT of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/FILE


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/FILE](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/FILE) The AasReferableNonIdentifiables FILE of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## ReferableElement/MULTI_LANGUAGE_PROPERTY
 Property with a value that can be provided in multiple languages.

 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/MULTI_LANGUAGE_PROPERTY](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/MULTI_LANGUAGE_PROPERTY) The AasReferableNonIdentifiables MULTI_LANGUAGE_PROPERTY of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/OPERATION


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/OPERATION](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/OPERATION) The AasReferableNonIdentifiables OPERATION of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/PROPERTY


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/PROPERTY](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/PROPERTY) The AasReferableNonIdentifiables PROPERTY of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/RANGE


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/RANGE](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/RANGE) The AasReferableNonIdentifiables RANGE of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/REFERENCE_ELEMENT


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/REFERENCE_ELEMENT](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/REFERENCE_ELEMENT) The AasReferableNonIdentifiables REFERENCE_ELEMENT of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/RELATIONSHIP_ELEMENT


 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/RELATIONSHIPT_ELEMENT](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/RELATIONSHIPT_ELEMENT) The AasReferableNonIdentifiables RELATIONSHIPT_ELEMENT of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/SUBMODEL_ELEMENT

 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/SUBMODEL_ELEMENT](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/SUBMODEL_ELEMENT) The AasReferableNonIdentifiables SUBMODEL_ELEMENT of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.

## AasReferableNonIdentifiables/SUBMODEL_ELEMENT_COLLECTION
 Collection of Submodel Elements

 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/SUBMODEL_ELEMENT_COLLECTION](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/SUBMODEL_ELEMENT_COLLECTION) The AasReferableNonIdentifiables SUBMODEL_ELEMENT_COLLECTION of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.
 
## AasReferableNonIdentifiables/SUBMODEL_ELEMENT_LIST
 List of set of Submodel Elements

 [http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/SUBMODEL_ELEMENT_LIST](http://admin-shell.io/aas/3/0/AasReferableNonIdentifiables/SUBMODEL_ELEMENT_LIST) The AasReferableNonIdentifiables SUBMODEL_ELEMENT_LIST of the AasReferableNonIdentifiables class as defined in IDTA-01001-3-0.



```

2024-11-25 17:45 UTC, BirgitBoss commented on aas/3/0/README.md
> +
```suggestion

```

2024-11-25 17:45 UTC, BirgitBoss commented on aas/3/0/README.md
> +
renamed to AasIdentifiables

2024-11-28 16:41 UTC, sebbader-sap commented on aas/3/0/README.md
> + [http://admin-shell.io/aas/3/0/AssetAdministrationShell/submodel](http://admin-shell.io/aas/3/0/AssetAdministrationShell/submodel) The attribute submodel of the AssetAdministrationShell class as def
The "UML" says AssetAdministrationShell/submodel (https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/core.html#aas_attributes), submodels is only in JSON. That's why I stick to the singular form.

2024-11-28 16:42 UTC, sebbader-sap commented on aas/3/0/README.md
> +## AssetKind/INSTANCE
No, that doesn't make sense. Whatever the specifications states shall also appear here.

2024-11-28 17:12 UTC, sebbader-sap commented on aas/3/0/README.md
> +## Range/min
I sorted it following the lexical order: "Range/max" < "Range/min"...

2024-11-29 15:49 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +This is the sub-namespace reserved for the "Asset Administration Shell - Part 2 Application Programming Interfaces Version 3.0".
```suggestion
This is the sub-namespace reserved for the "Specification of the Asset Administration Shell - Part 2: Application Programming Interfaces", Version 3.0 (IDTA-01002-3-0).
```

2024-11-29 15:50 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +The document 'Details of the Asset Administration Shell Part 2 - Application Programming Interfaces' [1] defines the meaning of its content and the used identifiers.
```suggestion
The document 'Specification of the Asset Administration Shell - Part 2: Application Programming Interfaces', Version 3.0 (IDTA-01002-3-0) [1] defines the meaning of its content and the used identifiers.
```

2024-11-29 15:50 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +Part 2'. Only identifiers that are defined in this document are allowed in this
```suggestion
The content of this area is defined in the "Specification of the Asset Administration Shell - Part 2: Application Programming Interfaces", Version 3.0 (IDTA-01002-3-0). Only identifiers that are defined in this document are allowed in this
```

2024-11-29 15:52 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +[https://admin-shell.io/aas/API/DataTypes/Endpoint/3/0](https://admin-shell.io/aas/API/DataTypes/Endpoint/3/0): The endpoint description of a network resource.
```suggestion
[https://admin-shell.io/aas/API/DataTypes/Endpoint/3/0](https://admin-shell.io/aas/API/DataTypes/Endpoint/3/0): The endpoint description of a network resource
```

2024-11-29 15:53 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +[https://admin-shell.io/aas/API/DataTypes/ProtocolInformation/3/0](https://admin-shell.io/aas/API/DataTypes/ProtocolInformation/3/0): The protocol information of a network resource endpoint will be d
```suggestion
[https://admin-shell.io/aas/API/DataTypes/ProtocolInformation/3/0](https://admin-shell.io/aas/API/DataTypes/ProtocolInformation/3/0): The protocol information of a network resource endpoint
```

2024-11-29 15:54 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +The entries of this sub-namespace have been created by [Sebastian Bader](https://github.com/sebbader)
this is visible from history of committs. Shouldn't it be IDTA in this case?

2024-11-29 15:54 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +on behalf of the IDTA Working Group 'Asset Administration Shell'.
```suggestion
on behalf of the IDTA Working Group 'Specifications of the Asset Administration Shell'.
```

2024-11-29 15:55 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +['Details of the Asset Administration Shell Part 2: Application Programming Interfaces'](https://industrialdigitaltwin.org/en/content-hub/aasspecifications), Version 3.0,
```suggestion
['Specification of the Asset Administration Shell - Part 2: Application Programming Interfaces'](https://industrialdigitaltwin.org/en/content-hub/aasspecifications), Version 3.0,
```

2024-11-29 15:55 UTC, BirgitBoss commented on aas/API/3/0/README.md
> +[1] S. Bader, B. Berres, B. Boss, A. Graf Gatterburg, M. Hoffmeister et al.
There are not authors mentioned in the published document

2024-11-29 15:56 UTC, BirgitBoss commented on aas/API/3/README.md
> +The document 'Details of the Asset Administration Shell Part 2 - Application Programming Interfaces' [1] defines the meaning of its content and the used identifiers.
```suggestion
The document 'Specification of the Asset Administration Shell Part 2 - Application Programming Interfaces' [1] defines the meaning of its content and the used identifiers.
```

2024-11-29 15:56 UTC, BirgitBoss commented on aas/API/3/README.md
> +The entries of this sub-namespace have been created by [Sebastian Bader](https://github.com/sebbader)
see above

2024-11-29 15:56 UTC, BirgitBoss commented on aas/API/3/README.md
> +on behalf of the IDTA Working Group 'Asset Administration Shell'.
```suggestion
on behalf of the IDTA Working Group 'Specifications of the Asset Administration Shell'.
```

2024-11-29 16:26 UTC, BirgitBoss commented on aas/API/README.md
> +on behalf of the IDTA Working Group 'Asset Administration Shell'.
```suggestion
on behalf of the Workstream "Specification of the Asset Administration Shell" in the IDTA Working Group 'Open Technology'.
```

2024-11-29 16:27 UTC, BirgitBoss requested changes
minor changes, see comments - mainly titles and names

2024-11-29 17:35 UTC, sebbader-sap commented on aas/API/3/0/README.md
> +The entries of this sub-namespace have been created by [Sebastian Bader](https://github.com/sebbader)
I think there wasn't an IDTA when I initially wrote this :-)

2024-11-29 17:54 UTC, sebbader-sap commented on aas/API/1/0/README.md
> +['Details of the Asset Administration Shell Part 2, Interoperability at Runtime –
I removed the 1.0RCs

2024-11-29 20:51 UTC, BirgitBoss requested changes

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## DataTypeIEC61360/BOOLEAN_IEC6360_DATATYPE
IEC61360 not IEC6360: for all values 

Why do we add _IEC61360 and DATATYPE at all? The enumeration vale is just BOOLEAN?

https://admin-shell-io.github.io/aas-specs-antora/IDTA-01003-a/v3.1/specification.html#_enumeration_data_type_iec61360

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## Entity/specificAssetId
Add empty line

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## Extension/name
Add empty line

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## IdentifierType
IdentifierType and its values not part of spec any longer:  remove

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## IdentifierKeyValuePair
Not existing any longer

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> + Enumeration of different level types within a DataSpecificationIEC61360. Contains Min, Max, Nom, and Typ.
No enumeration any longer but attributes still there

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## LocalKeyType
Not existing any longer

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## ModelingKind/TEMPLATE
Instance not in capital letters

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/0/README.md
> +## Qualifiable
Add empty line

2024-11-29 20:51 UTC, BirgitBoss commented on aas/3/README.md
> +Currently, one revision is in place as a Release Candidate.
Remove, 3/0 is no release candidate

2024-11-29 20:51 UTC, BirgitBoss commented on aas/API/README.md
> +This is the sub-namespace reserved for the "Asset Administration Shell - Part 2: Application Programming Interfaces".
Use correct naming "Specification of the Asset Administration Shell...

2024-11-29 20:51 UTC, BirgitBoss commented on aas/README.md
> +[1] ['Details of the Asset Administration Shell Part 1, The exchange of information
Use correct naming

2024-11-29 20:51 UTC, BirgitBoss commented on aas/README.md
> +[4] ['Details of the Asset Administration Shell Part 1, The exchange of information
Use correct title

2024-12-14 17:22 UTC, BirgitBoss commented on aas/README.md
> +between partners in the value chain of Industrie 4.0'](https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V3.html), Version 3.0,
```suggestion
[4] ['Specification of the Asset Administration Shell - Part 1: Metamodel'](https://industrialdigitaltwin.org/en/content-hub/aasspecificationsl), Version 3.0,
```

2024-12-14 17:24 UTC, BirgitBoss commented on aas/README.md
> +between partners in the value chain of Industrie 4.0'](https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V3.html), Version 3.0,
```suggestion
[4] ['Specification of the Asset Administration Shell - Part 1: Metamodel'](https://industrialdigitaltwin.org/en/content-hub/aasspecifications), Version 3.0,
```

2024-12-14 17:25 UTC, BirgitBoss commented on aas/README.md
>  Plattform Industrie 4.0, ZVEI, 2018
```suggestion
[4] ['Specification of the Asset Administration Shell - Part 1: Metamodel'](https://industrialdigitaltwin.org/en/content-hub/aasspecifications), Version 3.0,
```

2025-01-25 22:03 UTC, BirgitBoss commented
use https://github.com/admin-shell-io/id/pull/37 instead

2025-01-25 23:07 UTC, merged